package me.phie.tawc.licenses

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject

/**
 * The parsed contents of `assets/licenses.json`, generated by
 * `scripts/gen-third-party-licenses.sh`. See notes/licensing.md for why
 * the app ships this at all.
 *
 * Components are pre-grouped by license family so the UI can offer an
 * index of a dozen entries instead of one endless page. Parsing the
 * whole document costs enough (~700 KB of JSON) that it is cached for
 * the process: the index screen loads it, and the section screen reuses
 * it rather than parsing again on every tap.
 */
object LicenseDoc {

    /**
     * A run of license text. [pre] text kept its original line breaks
     * (lists, headers, ASCII layout) and wants a monospace, verbatim
     * rendering; the rest is prose the generator unwrapped so the screen
     * can rewrap it to whatever width it has.
     */
    data class Block(val pre: Boolean, val text: String)

    /** One distinct license text, plus every component it covers. */
    data class Entry(val components: List<String>, val blocks: List<Block>)

    data class Section(val title: String, val subtitle: String, val entries: List<Entry>)

    data class Doc(
        val intro: List<String>,
        val sourceUrl: String,
        val sections: List<Section>,
    )

    @Volatile
    private var cached: Doc? = null

    fun load(context: Context): Doc =
        cached ?: synchronized(this) {
            cached ?: parse(
                context.applicationContext.assets
                    .open(ASSET)
                    .bufferedReader()
                    .use { it.readText() },
            ).also { cached = it }
        }

    private fun parse(json: String): Doc {
        val root = JSONObject(json)
        return Doc(
            intro = root.getJSONArray("intro").strings(),
            sourceUrl = root.getString("sourceUrl"),
            sections = root.getJSONArray("sections").map { section ->
                Section(
                    title = section.getString("title"),
                    subtitle = section.getString("subtitle"),
                    entries = section.getJSONArray("entries").map { entry ->
                        Entry(
                            components = entry.getJSONArray("components").strings(),
                            blocks = entry.getJSONArray("blocks").map { block ->
                                Block(
                                    pre = block.getBoolean("pre"),
                                    text = block.getString("text"),
                                )
                            },
                        )
                    },
                )
            },
        )
    }

    private fun JSONArray.strings(): List<String> = List(length()) { getString(it) }

    private fun <T> JSONArray.map(transform: (JSONObject) -> T): List<T> =
        List(length()) { transform(getJSONObject(it)) }

    private const val ASSET = "licenses.json"
}
